# Generated by Django 4.2.4 on 2023-11-02 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bankaccounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', shortuuid.django_fields.ShortUUIDField(alphabet=None, length=12, max_length=25, prefix='DIPY', unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[['FAILED', 'failed'], ['COMPLETED', 'completed'], ['PENDING', 'processing'], ['REQUEST_SENT', 'request_sent'], ['REQUEST_PROCESSING', 'request_processing']], default='pending', max_length=200)),
                ('transaction_type', models.CharField(choices=[['transfer', 'TRANSFER'], ['withdraw', 'WITHDRAW'], ['refund', 'REFUND'], ['received', 'RECEIVED'], ['request', 'REQUEST'], ['none', 'NONE']], default=None, max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('receiver', models.ForeignKey(max_length=200, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiver', to=settings.AUTH_USER_MODEL)),
                ('receiver_account', models.ForeignKey(max_length=200, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_amount', to='bankaccounts.account')),
                ('sender', models.ForeignKey(max_length=200, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender', to=settings.AUTH_USER_MODEL)),
                ('sender_account', models.ForeignKey(max_length=200, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender_amount', to='bankaccounts.account')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', shortuuid.django_fields.ShortUUIDField(alphabet='123456789', length=10, max_length=20, prefix='CRED', unique=True)),
                ('name', models.CharField(max_length=200)),
                ('number', shortuuid.django_fields.ShortUUIDField(alphabet=None, length=12, max_length=16, prefix='CCNO', unique=True)),
                ('month', models.CharField(max_length=15)),
                ('year', models.IntegerField()),
                ('CVV', shortuuid.django_fields.ShortUUIDField(alphabet='123456789', length=3, max_length=6, prefix='', unique=True)),
                ('card_type', models.CharField(choices=[['MASTER', 'master'], ['VISA', 'visa'], ['RUPAY', 'rupay'], ['PLATINUM', 'platinum']], max_length=50)),
                ('card_status', models.CharField(choices=[['ACTIVE', 'active'], ['DEACTIVE', 'deactive']], max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
