# Generated by Django 4.2.4 on 2023-09-20 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bankaccounts', '0002_kyc'),
    ]

    operations = [
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', shortuuid.django_fields.ShortUUIDField(alphabet=None, length=12, max_length=25, prefix='DIPY', unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[['FAILED', 'failed'], ['COMPLETED', 'completed'], ['PENDING', 'processing'], ['REQUEST_SENT', 'request_sent'], ['REQUEST_PROCESSING', 'request_processing']], default='pending', max_length=200)),
                ('transaction_type', models.CharField(choices=[['transfer', 'TRANSFER'], ['withdraw', 'WITHDRAW'], ['refund', 'REFUND'], ['received', 'RECEIVED'], ['request', 'REQUEST'], ['none', 'NONE']], default=None, max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(blank=True, null=True)),
                ('received_amount', models.ForeignKey(max_length=200, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_amount', to='bankaccounts.account')),
                ('receiver', models.ForeignKey(max_length=200, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(max_length=200, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender', to=settings.AUTH_USER_MODEL)),
                ('sender_amount', models.ForeignKey(max_length=200, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender_amount', to='bankaccounts.account')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
