# Generated by Django 4.2.4 on 2023-09-28 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_alter_transaction_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='received_amount',
            new_name='received_account',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='sender_amount',
            new_name='sender_account',
        ),
    ]
