# Generated by Django 4.2.4 on 2023-10-01 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_rename_received_amount_transaction_received_account_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='received_account',
            new_name='receiver_account',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
