# Generated by Django 4.2.4 on 2023-10-12 05:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transaction', '0004_rename_received_account_transaction_receiver_account_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', shortuuid.django_fields.ShortUUIDField(alphabet='123456789', length=10, max_length=20, prefix='CRED', unique=True)),
                ('name', models.CharField(max_length=200)),
                ('number', shortuuid.django_fields.ShortUUIDField(alphabet=None, length=12, max_length=16, prefix='CCNO', unique=True)),
                ('month', models.DateField()),
                ('year', models.DateField()),
                ('CVV', shortuuid.django_fields.ShortUUIDField(alphabet='123456789', length=3, max_length=6, prefix='', unique=True)),
                ('card_type', models.CharField(choices=[['MASTER', 'master'], ['VISA', 'visa'], ['RUPAY', 'rupay'], ['PLATINUM', 'platinum']], max_length=50)),
                ('card_status', models.CharField(choices=[['ACTIVE', 'active'], ['DEACTIVE', 'deactive']], max_length=200)),
                ('date', models.DateField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
