# Generated by Django 4.2.4 on 2023-10-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_creditcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='month',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='year',
            field=models.IntegerField(),
        ),
    ]
