# Generated by Django 4.2.4 on 2023-10-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_alter_creditcard_month_alter_creditcard_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
