# Generated by Django 4.2.4 on 2023-08-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digipayapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forms',
            name='rs',
        ),
        migrations.AddField(
            model_name='forms',
            name='address',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forms',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='forms',
            name='phone_number',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='forms',
            name='age',
            field=models.PositiveIntegerField(),
        ),
    ]
